#################################################################
#
# file       : Open Core Engine Makefile
# Created on : Dec 11, 2017
# Copyright (c) UBIqube 2017
# 
#################################################################


SMS_BASE = $(shell pwd)
MAKE_DEFAULT = ${SMS_BASE}/Make-default.mk
SB_ROOT = ${SMS_BASE}

SUBDIRS = smsd

-include ${MAKE_DEFAULT}
