	/**
	 * Copyright UBIqube Solutions 2016
	 * @file error.h
	 * Creation Date: Dec 11, 2017
	 */
	/* Automatically generated by error_list.php */

	#ifndef ERROR_H_
	#define ERROR_H_

  #ifdef __cplusplus
  extern "C"{
  #endif

	/** User error codes.
	 * First digit is error type:
	 * @arg @e 1 @b USER command (VERB)
	 * @arg @e 2 @b DATABASE (DB)
	 * @arg @e 4 @b SD
	 * @arg @e 8 @b SOC
	 * @addtogroup errorlist    Errors from SMS to user
	 * @{
	 */
	enum error_id
	{
  SMS_OK = 0,      /**< OK<br>0x00000000 */
  ERR_NETWORK = 1,      /**< ERROR<br>0x00000001 */
  OBN_NOT_REACHABLE = 2,      /**< OBN reachability Failed<br>0x00000002 */
  ERR_DB_FAILED = 3,      /**< Database operation failed<br>0x20000001 */
  ERR_DB_NOTFOUND = 4,      /**< device not found in the database<br>0x20000002 */
  ERR_DB_CONNECTION_LOST = 5,      /**< Database connection lost<br>0x20000003 */
  ERR_DB_MORE_THAN_ONE = 6,      /**< Multiple entries found in the database<br>0x20000004 */
  ERR_DB_WRONG_DMSA_NODE = 7,      /**< The device is not managed by this DMSA node<br>0x20000005 */
  ERR_DB_MAINTENANCE_MODE = 8,      /**< The device is in maintenance mode<br>0x20000006 */
  ERR_VERB_UNKNWN = 9,      /**< Unknown verb<br>0x10000001 */
  ERR_VERB_BAD_PARAM = 10,      /**< Bad parameters on command<br>0x10000002 */
  ERR_VERB_SINGLE_CALL = 11,      /**< A similar command is already running<br>0x10000003 */
  SMS_RUNNING = 12,      /**< A process is still running<br>0x10000004 */
  ERR_LOCAL_SSH = 13,      /**< Local ssh connection failed<br>0x80000001 */
  ERR_LOCAL_CMD = 14,      /**< Local command failed<br>0x80000002 */
  ERR_LOCAL_PHP = 15,      /**< Local command failed (script)<br>0x80000003 */
  ERR_LOCAL_PATTERN_NOT_FOUND = 16,      /**< Pattern not found<br>0x80000004 */
  ERR_LOCAL_RACONNLOST = 17,      /**< Connection with RA server lost<br>0x80000005 */
  ERR_LOCAL_CAREQFAILED = 18,      /**< CA server request failed<br>0x80000006 */
  ERR_LOCAL_RAOTP = 19,      /**< RA OTP request failed<br>0x80000007 */
  ERR_LOCAL_FILE = 20,      /**< local file access failed<br>0x80000008 */
  ERR_LOCAL_MEMORY = 21,      /**< local memory allocation failed<br>0x80000009 */
  ERR_LOCAL_CONFIG = 22,      /**< local configuration failed<br>0x8000000A */
  ERR_LOCAL_NOT_FOUND = 23,      /**< Not found<br>0x8000000B */
  ERR_LOCAL_FILE_FORMAT = 24,      /**< Bad format for local file<br>0x8000000C */
  ERR_DEGRADED_MODE = 25,      /**< The SMS is in degraded mode<br>0x8000000D */
  ERR_LOCAL_TEMPLATE = 26,      /**< Error found in template or object file<br>0x8000000E */
  ERR_LOCAL_VM_UNAVAIL = 27,      /**< No local VM available<br>0x8000000F */
  ERR_SD_NOT_SUPPORTED = 28,      /**< Function not supported by the device<br>0x40000001 */
  ERR_SD_BADSSHKEY = 29,      /**< The SSH key does not match the one stored in database<br>0x40000002 */
  ERR_SD_NETWORK = 30,      /**< device unreachable (network error)<br>0x40000003 */
  ERR_SD_PROVLOCK = 31,      /**< Initial provisioning is needed<br>0x40000004 */
  ERR_SD_LOCK = 32,      /**< An update is already running<br>0x40000005 */
  ERR_SD_FAILED = 33,      /**< Operation Failed<br>0x40000006 */
  ERR_SD_AUTH = 34,      /**< Authentication failed<br>0x40000007 */
  ERR_SD_TFTP = 35,      /**< TFTP transfer failed<br>0x40000008 */
  ERR_SD_ADM_AUTH = 36,      /**< Admin Authentication failed<br>0x40000009 */
  ERR_SD_SSHDIALOG = 37,      /**< SSH dialog failed (can be incompatible SSH version)<br>0x4000000A */
  ERR_SD_GETSSHKEY = 38,      /**< Cannot get SSH KEY<br>0x4000000B */
  ERR_SD_TIMEOUTCONNECT = 39,      /**< device unreachable (Connection timeout)<br>0x4000000C */
  ERR_SD_CONNREFUSED = 40,      /**< device unreachable (Connection refused)<br>0x4000000D */
  ERR_SD_NOIP = 41,      /**< device unreachable (no ip address configured)<br>0x4000000E */
  ERR_SD_CERTGEN = 42,      /**< Certificate generation failed<br>0x4000000F */
  ERR_SD_KEYGEN = 43,      /**< Key generation failed<br>0x40000010 */
  ERR_SD_CERTSCEP = 44,      /**< SCEP Certificate generation failed<br>0x40000011 */
  ERR_SD_INTRUPDT = 45,      /**< The update of the device has been interrupted<br>0x40000012 */
  ERR_SD_CMDTMOUT = 46,      /**< Command timeout on the device<br>0x40000013 */
  ERR_SD_SNMP = 47,      /**< device unreachable (snmp filtered or disabled or bad community)<br>0x40000014 */
  ERR_SD_NOT_CONFIGURED = 48,      /**< Function not configured for this device<br>0x40000015 */
  ERR_SD_SCP = 49,      /**< SCP transfer failed<br>0x40000016 */
  ERR_SD_CMDFAILED = 50,      /**< Command failed on the device<br>0x40000017 */
  ERR_SD_BAD_HOSTNAME = 51,      /**< Bad hostname<br>0x40000018 */
  ERR_SD_ADDON_NETWORK = 52,      /**< Addon board on the device is unreachable (network error)<br>0x40000019 */
  ERR_SD_ENOMEM = 53,      /**< Not enough memory or flash or disk space on the device<br>0x4000001A */
  ERR_SD_NEED_UPDATE = 54,      /**< Device update is scheduled<br>0x4000001B */
  ERR_SD_FILE_TRANSFER = 55,      /**< File transfer to device failed<br>0x4000001C */
  ERR_SD_BAD_SERIAL_NUMBER = 56,      /**< Device has bad serial number<br>0x4000001D */
  ERR_SD_BAD_VERSION = 57,      /**< Device has bad version<br>0x4000001E */
  ERR_SD_CONN_CLOSED_BY_PEER = 58,      /**< Connection closed by peer<br>0x4000001F */
  ERR_SD_BAD_FILE_URI = 59,      /**< Attached file repository path is not valid<br>0x40000020 */
  ERR_SD_PERMISSION_DENIED = 60,      /**< Permission denied<br>0x40000021 */
  ERR_SD_VM_NOT_FOUND = 61,      /**< VM not found<br>0x40000022 */
  ERR_SD_HA_SWAP = 62,      /**< HA swap not done<br>0x40000023 */
  ERR_SD_GATEWAY_UNREACHABLE = 63,      /**< Gateway server unreachable - Update failed <br>0x40000024 */
  ERR_SD_GATEWAY = 64,      /**< Gateway Server Error - Update failed<br>0x40000025 */
  ERR_SD_LICENSE_EXPIRED = 65,      /**< License has expired<br>0x40000026 */
  ERR_SD_PARSING_FAILED = 66,      /**< Parsing failed during license update, Aborting<br>0x40000027 */
  ERR_SD_CONF_NO_CHANGES = 67,      /**< No changes detected from current configuration<br>0x40000028 */
  ERR_SD_FIRMWARE_NO_MANIFEST_SERVER = 68,      /**< Failed to connect to manifest server during firmware upgrade<br>0x40000029 */
  ERR_SD_FIRMWARE_NO_UPGRADES = 69,      /**< No Available upgrades for firmware upgrade<br>0x4000002A */
  ERR_SD_AUTH_MANIFEST_SERVER = 70,      /**< Failed to authenticate with manifest server<br>0x4000002B */
  ERR_SD_NO_BACKUP_PARTITION = 71,      /**< Backup partition doesn't exist on the device<br>0x4000002C */
  ERR_SD_DNS_ERROR = 72,      /**< Failure downloading upgrade list: DNS lookup failed<br>0x4000002D */
  ERR_SD_LICENSE_UPDATE = 73,      /**< License update failed<br>0x4000002E */
  ERR_SD_CERT_UPLOAD_FILENOTFOUND = 74,      /**< File not found on tftp server<br>0x4000002F */
  ERR_SD_CERT_UPLOAD_CERTEXIST = 75,      /**< Certificate already exists<br>0x40000030 */
  ERR_SD_CERT_UPLOAD_CANNOTREAD_CERT = 76,      /**< Cannot read certificate file<br>0x40000031 */
  ERR_SD_CERT_IMPORT_FAIL = 77,      /**< Import local certificate failed<br>0x40000032 */
  ERR_SD_CERT_UPLOAD_CANNOTREAD_PKCS = 78,      /**< Error reading PKCS#12 file<br>0x40000033 */
  ERR_SD_CERT_UPLOAD_MACVERIF_FAIL = 79,      /**< MAC verify failure<br>0x40000034 */
  ERR_CONFIG_EMPTY = 80,      /**< No configuration attached to the device<br>0x01000001 */
  ERR_NO_FIRMWARE = 81,      /**< No firmware attached to the device<br>0x01000002 */
  ERR_FIRMWARE_CORRUPTED = 82,      /**< The firmware attached to the device is corrupted<br>0x01000003 */
  ERR_RESTORE_FAILED = 83,      /**< The configuration restore has failed<br>0x01000004 */
  ERR_CONFIGURATION_INVALID = 84,      /**< The configuration to apply is invalid<br>0x01000005 */
  ERR_CONFIG_VAR_UNDEFINED = 85,      /**< The configuration contains undefined variables<br>0x01000006 */
  ERR_UPGRADE_IPS_SIG_PACK_FAILED = 86,      /**< Upgrading new IPS signature pack failed<br>0x01000007 */

      ERR_END = 87
	};
	/**
	 * @}
	 */

  #ifdef __cplusplus
  }
  #endif

	#endif /* ERROR_H_ */
